/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bfst22.vector;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AddressTest {
    @Test
    void itu() {
        var addr = Address.parse("Rued Langgaards Vej 7, 2300 København S");
        assertEquals("Rued Langgaards Vej", addr.street);
        assertEquals("7", addr.house);
        assertEquals("2300", addr.postcode);
        assertEquals("København S", addr.city);
    }

    @Test
    void ituComma() {
        var addr = Address.parse("Rued Langgaards Vej 7,  ,  2300 København S");
        assertEquals("Rued Langgaards Vej", addr.street);
        assertEquals("7", addr.house);
        assertEquals("2300", addr.postcode);
        assertEquals("København S", addr.city);
    }

    @Test
    void ituSimple() {
        var addr = Address.parse("Rued Langgaards Vej 7");
        assertEquals("Rued Langgaards Vej", addr.street);
        assertEquals("7", addr.house);
    }

    @Test
    void ituApartment() {
        var addr = Address.parse("Rued Langgaards Vej 7A, 23.th, 2300 København S");
        assertEquals("Rued Langgaards Vej", addr.street);
        assertEquals("7A", addr.house);
        assertEquals("23", addr.floor);
        assertEquals("th", addr.side);
        assertEquals("2300", addr.postcode);
        assertEquals("København S", addr.city);
    }

    @Test
    void noCity() {
        var addr = Address.parse("Rued Langgaards Vej 7A, 23.th.");
        assertEquals("Rued Langgaards Vej", addr.street);
        assertEquals("7A", addr.house);
        assertEquals("23", addr.floor);
        assertEquals("th", addr.side);
    }

}
