/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bfst22.vector;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class SHAD {
    @Test void itu() {
        var addr = Address.parse("Rued Langgaards Vej 7, 2300 København S");
        assertEquals("Rued Langgaards Vej", addr.street);
        assertEquals("7", addr.house);
        assertEquals("2300", addr.postcode);
        assertEquals("København S", addr.city);

        addr = Address.parse("Rosebakken 7, 3700 Aabakken");
        assertEquals("Rosebakken", addr.street);
        assertEquals("7", addr.house);
        assertEquals("3700", addr.postcode);
        assertEquals("Aabakken", addr.city);

        addr = Address.parse("10. Februar Vej 11, 6700 Christiansfeld");
        assertEquals("10. Februar Vej", addr.street);
        assertEquals("11", addr.house);
        assertEquals("6700", addr.postcode);
        assertEquals("Christiansfeld", addr.city);

        addr = Address.parse("10. Randersgade 11, 2100 København Ø ");
        assertEquals("10. Randersgade", addr.street);
        assertEquals("11", addr.house);
        assertEquals("2100", addr.postcode);
        assertEquals("København Ø", addr.city);
    }
    @Test void ituComma() {
        var addr = Address.parse("Rued Langgaards Vej    7 ,  , 2300     København S");
        assertEquals("Rued Langgaards Vej", addr.street);
        assertEquals("7", addr.house);
        assertEquals("2300", addr.postcode);
        assertEquals("København S", addr.city);

        addr = Address.parse("Rosebakken    7 ,  , 3700     Aabakken");
        assertEquals("Rosebakken", addr.street);
        assertEquals("7", addr.house);
        assertEquals("3700", addr.postcode);
        assertEquals("Aabakken", addr.city);

        addr = Address.parse("10. Februar Vej    11 ,  , 6700     Christiansfeld");
        assertEquals("10. Februar Vej", addr.street);
        assertEquals("11", addr.house);
        assertEquals("6700", addr.postcode);
        assertEquals("Christiansfeld", addr.city);

        addr = Address.parse("10. Randersgade    11 ,  , 2100     København Ø");
        assertEquals("10. Randersgade", addr.street);
        assertEquals("11", addr.house);
        assertEquals("2100", addr.postcode);
        assertEquals("København Ø", addr.city);


    }
    @Test void ituSimple() {
        var addr = Address.parse("Rued Langgaards Vej 7");
        assertEquals("Rued Langgaards Vej", addr.street);
        assertEquals("7", addr.house);

        addr = Address.parse("Rosebakken 7");
        assertEquals("Rosebakken", addr.street);
        assertEquals("7", addr.house);

        addr = Address.parse("10. Februar Vej 11");
        assertEquals("10. Februar Vej", addr.street);
        assertEquals("11", addr.house);

        addr = Address.parse("10. Randersgade 11");
        assertEquals("10. Randersgade", addr.street);
        assertEquals("11", addr.house);
    }
}
